[package]
name = "libzfs"
version = "0.4.0"
authors = ["IML Team <iml@intel.com>"]
description = "Rust wrapper around libzfs-sys"
license = "MIT"

[dependencies]
libzfs-sys = { path = "../libzfs-sys", version = "0.3.0" }
nvpair-sys = "0.1"
serde = "1.0"
serde_derive = "1.0"
foreign-types = "0.3"
cstr-argument = "0.0"
