[package]
name = "libzfs-sys"
version = "0.3.0"
description = "Rust bindings to libzfs2"
license = "MIT"
repository = "https://github.com/intel-hpdd/rust-libzfs"
authors = ["Iml Team <iml@intel.com>"]
links = "zfs"
build = "build.rs"

[dependencies]
nvpair-sys = "0.1"

[build-dependencies]
bindgen = "0.30.0"
pkg-config = "0.3"
